import { createCommandConfig, logger } from 'robo.js'

export const config = createCommandConfig({
	description: 'mans did NOT say this',
})

export default (interaction) => {
	logger.info(`Blursed quote generated by ${interaction.user}`)
		const quotes = [
		"I like men.",
		"Racism IS the NEW meta.",
		"fuck tuxxegobot.",
		"assembly > realm.",
		"I can't pull.",
		"HOP ON CONTENT WARNING!",
		"lethal? like a lethal company?",
		"this response list is massive.",
		"I love lazy",
		"when is gta 6 dropping",
		"ERROR404ERROR404ERROR40- haha gotchu",
		];

		const randomQuote = quotes[Math.floor(Math.random() * quotes.length)];
		interaction.reply(`"${randomQuote}"\n- ${interaction.user}`);
	  };