import { createCommandConfig, logger } from 'robo.js'

export const config = createCommandConfig({
	description: 'making a list, checking it twice!',
	options: [{
		name: 'user',
		description: 'target',
		type: 'user',
		required: true
	},
    {
        name: 'list',
        description: 'naughty or nice? be sure to check twice!',
        type: 'string',
        choices: [
            { name: 'nice list', value: 'nice list' },
            { name: 'naughty list', value: 'naughty list' }
        ],
        required: true
    }]
})

export default (interaction) => {
	logger.info(`list generated by ${interaction.user}`)
	const user = interaction.options.getUser('user');

    if (interaction.options.getString('list').includes("nice list")) {
        interaction.reply(`${user} placed on the nice list!`)
    }
    else if(interaction.options.getString('list').includes("naughty list")) {
        interaction.reply(`${user} placed on the naughty list!`)
    }
};