import { createCommandConfig, logger } from 'robo.js';

export const config = createCommandConfig({
	description: 'are you meant to be?',
	options: [
		{
			name: 'partner1',
			description: 'rizzler',
			type: 'user',
			required: true
		},
		{
			name: 'partner2',
			description: 'rizzed',
			type: 'user',
			required: false
		}
	]
});

export default (interaction) => {
	logger.info(`match generated by ${interaction.user.tag}`);

	const partner1 = interaction.options.getUser('partner1');
	const partner2 = interaction.options.getUser('partner2') || interaction.user;

	const getRandomIntInclusive = (min, max) =>
		Math.floor(Math.random() * (max - min + 1) + min);

	const rating = getRandomIntInclusive(1, 100);

	const matchMessages = {
		25: ["I'd reconsider.", "Did you come up short?", "Gonna need a prenup"],
		50: ["Try someone uglier next time?", "Invest in flowers", "Getting warmer"],
		75: ["What is this rizz?", "Good chemistry!", "Make a reservation"],
		99: ["Tap already.", "Get a room", "Hotshot"],
		100: ["You're perfect!", "Baby time!", "Who's top?"]
	};

	let messagePool;
	let emoji;

	if (rating <= 25) {
		messagePool = matchMessages[25];
		emoji = ":broken_heart:";
	} else if (rating <= 50) {
		messagePool = matchMessages[50];
		emoji = ":mending_heart:";
	} else if (rating <= 75) {
		messagePool = matchMessages[75];
		emoji = ":gift_heart:";
	} else if (rating <= 99) {
		messagePool = matchMessages[99];
		emoji = ":heartpulse:";
	} else {
		messagePool = matchMessages[100];
		emoji = ":sparkling_heart:";
	}

	const quote = messagePool[Math.floor(Math.random() * messagePool.length)];

	interaction.reply(`${partner1} ❤ ${partner2}\n${emoji} ${rating}%\n> ${quote}`);
};